# Generated by Django 4.2.7 on 2023-11-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_genre_profile_gnere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='gnere',
            new_name='genre',
        ),
    ]
