# Generated by Django 4.2.7 on 2023-11-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_gnere_profile_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
