# Generated by Django 4.2.7 on 2023-11-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='genre',
        ),
        migrations.AddField(
            model_name='playlist',
            name='genre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
