# Generated by Django 4.2.7 on 2024-01-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlist", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
