# Generated by Django 4.2.7 on 2023-11-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='singer',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
