# Generated by Django 4.2.7 on 2023-11-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_playlist_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
