# Generated by Django 4.2.7 on 2023-11-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_remove_music_singer'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='sing',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='information',
            field=models.CharField(max_length=200),
        ),
    ]
