# Generated by Django 4.2.7 on 2023-11-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0005_music_sing_music_thumbnail_alter_music_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='sing',
            new_name='singer',
        ),
        migrations.AddField(
            model_name='music',
            name='song',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
