# Generated by Django 4.2.7 on 2023-11-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0006_rename_sing_music_singer_music_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='genre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
