# Generated by Django 4.2.7 on 2023-11-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0007_music_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
